### ISSUE TITLE
Settings not visible

### ISSUE THREAD

**Issue by w4rt** [Ninjabrain1/Ninjabrain-Bot#65] opened 2023-06-04 01:02 UTC
I open the .jar file and the main window opens up fine, I hit the gear icon and nothing pops up, yet on the taskbar it shows the settings window, but if I try to click on it nothing happens.

**Comment by w4rt** [comment] 2023-06-04 01:02
Version 1.4.1 by the way

**Comment by N0tJim** [comment] 2023-06-04 19:12
same here

**Comment by Ninjabrain1** [comment] 2023-06-04 19:15
@w4rt @N0tJim what OS and GPU do you have?

**Comment by N0tJim** [comment] 2023-06-05 15:47
> @w4rt @N0tJim what OS and GPU do you have?

Win10 no gpu, I run on ryzen 3 3200g graphics

**Comment by w4rt** [comment] 2023-06-06 21:30
Windows OS, AMD Radeon Graphics

**Comment by pardonw** [comment] 2023-06-09 08:14
same here

**Comment by w4rt** [comment] 2023-06-16 19:27
> @w4rt @N0tJim what OS and GPU do you have?
Also the icon for settings when I hover over the ninjabrain bot on the taskbar is the default .jar icon, as opposed to the videos showing the same icon as ninjabrain bot.

**Comment by GaymerKoala** [comment] 2023-07-11 17:12
I also have this problem and was wondering whether there was a way to fix this issue?

**Comment by Equinism** [comment] 2023-08-07 07:31
same here, the settings are there for me, but they are just completely invisible

**Comment by krankyy** [comment] 2023-08-29 16:17
@Ninjabrain1 i want you to fix this issue asap so ill provide some info, same issue: settings opens up but its invisible, but you still can toggle buttons and they will work.
one more thing i want to say that on my laptop, ninjabrain 1.3.2 everything works good, 1.4 does NOT work at all whatever i try, and 1.4.1 works except settings visibility.
my specs: Windows 10 pro(i think cracked), laptop, 
CPU: AMD Ryzen 5 5600H with Radeon Graphics 6 cores/12 threads
GPU(Integrated): AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc. (0x1002)) DriverVersion=27.20.14056.5 2048MB VRAM
GPU: NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA (0x10de)) DriverVersion=31.0.15.2896 4095MB VRAM

i hope this info will help you fix the issue faster

**Comment by Knawk** [comment] 2023-12-06 02:40
Unfortunately I don't have the right hardware to reproduce the bug myself, but it seems that there's a way to get more debug information that could get more information in the future:

> To receive verbose console output about whether the OpenGL-based pipeline is initialized successfully for a particular screen, set this property to True (note the uppercase T):
>
> `-Dsun.java2d.opengl=True`

(from Oracle's Java 2D docs: https://docs.oracle.com/javase/8/docs/technotes/guides/2d/flags.html#opengl)

**Comment by ohnishant** [comment] 2023-12-14 18:01
> > `-Dsun.java2d.opengl=True`
> 
> (from Oracle's Java 2D docs: https://docs.oracle.com/javase/8/docs/technotes/guides/2d/flags.html#opengl)

Tried running with v1.4.1  with the given flag. The logs were identical:  


```
_Macros> java -jar .\Ninjabrain-Bot-1.4.1.jar -Dsun.java2d.opengl=True

[main] Language: English
[Thread-3] Time to check for updates: 1.09 seconds.
null, false
[Clipboard reader] Time to construct prior: 0.002 seconds.
[Clipboard reader] Time to triangulate: 0.014 seconds.
[AWT-EventQueue-0] Time to construct prior: 0.0 seconds.
[AWT-EventQueue-0] Time to triangulate: 0.005 seconds.
```

Hardware spec-
CPU:  AMD Ryzen 5 3400G
GPU:  Radeon™ RX Vega 11 Graphics (Integrated)

Here is a screenshot. The settings window is just invisible but the taskbar has an entry for it
![image](https://github.com/Ninjabrain1/Ninjabrain-Bot/assets/52268717/cc52bd79-4f32-4eb5-89ef-ede2e502a9f8)

**Comment by MoordMachineYT** [comment] 2024-01-04 20:01
> java -jar .\Ninjabrain-Bot-1.4.1.jar -Dsun.java2d.opengl=True

The flag is set at the entry point of the script:

```java
System.setProperty("sun.java2d.opengl", "true");
```

I'm not too familiar with Java, but I'm guessing that the application is overwriting the flag as it loads, meaning the program needs to be recompiled before we can see those logs. 

On another note, is it normal that I can load multiple instances of the application, and could this be related?

**Comment by krankyy** [comment] 2024-01-12 17:53
Ok guys i found a way to make settings visible, i dont know how it's possible for others pc but i have a laptop and my reading mode(that makes blue light less brighter) is always on, and sometimes its just lags and makes my laptop like reboot but like in one second, its hard to explain ill try to catch it on recording, so when that happens i can see my settings

**Comment by krankyy** [comment] 2024-01-12 18:38
nevermind my settings work completely fine now, so i dont remember everything i did change on my laptop but i think that the problem is with the wrong java, there is .exe and .msi installers, when i downloaded .msi everything fixed
https://adoptium.net/temurin/releases/?os=windows
also you can try different java versions, but i dont reccomend it since ninbrain can just give up on working, unless you want to help finding solution

**Comment by krankyy** [comment] 2024-01-12 19:17
ok so everything you need to do is this : https://obsproject.com/kb/minecraft-java-edition-troubleshooting

**Comment by krankyy** [comment] 2024-01-12 19:17
ok so everything you need to do is this : https://obsproject.com/kb/minecraft-java-edition-troubleshooting

**Comment by dkurth** [comment] 2024-02-06 01:05
I tried installing Java from the link @krankyy provided.  Here's the output when I run `java -version`:

```
openjdk version "21.0.2" 2024-01-16 LTS
```

I also walked through the steps from the obsproject.com link.  However, I still cannot see the Settings window.  It seems like it is there, intercepting mouse clicks, but it's just not rendering to the screen.

I'm running:
- Windows 10 Home, version 22H2
- Processor: 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz   3.91 GHz

Any ideas of other things to try?

**Comment by krankyy** [comment] 2024-02-08 17:52
@dkurth just check the message  above you

**Comment by dkurth** [comment] 2024-02-08 18:45
> @dkurth just check the message above you

Thanks - Before commenting, I followed those instructions without success, but I think I know why.  For some reason, I had Minecraft running using an Oracle version of Java, but Ninjabrain-Bot was using an OpenJDK version.  I'll have to sort that out.

In the meantime, I just tried following those instructions again, but using my OpenJDK Java.  It worked... once.  I was able to see the settings screen.  But when I exited Ninjabrain-Bot and relaunched it, it is broken again.

I tried it again, this time running Ninjabrain-Bot using the Oracle Java, and again it worked... once.  So that is pretty strange.

Thanks for the help!  Now that I've seen the settings menu, I have some hope, but I'll need to experiment a bit.

**Comment by Cloud7-c** [comment] 2024-02-14 16:01
I've encountered the same issue. I found a solution:

Download the code(1.4.2) and remove line 23 from src/main/java/ninjabrainbot/Main.java

```java
System.setProperty("sun.java2d.opengl", sessionType.orElse("").equals("wayland") ? "false" : "True");
```
On my device, running this code sets `sun.java2d.opengl` to True. After removing it, it defaults to false. 

After recompiling, the settings window is able to open normally.

I'm not sure if there will be any side effects from doing this, but the modified Bot works fine on my device. 

Some device information here:
- Windows 11 Home Edition 22H2
- AMD Ryzen 7 4800U with Radeon Graphics

**Comment by dkurth** [comment] 2024-02-14 16:04
> I've encountered the same issue. I found a solution: ...

Thanks, I will give that a try!

**Comment by eshan1234567g** [comment] 2024-04-07 10:09
hi i also have issue with setting in 1.4.2 i open ninjabrinbot  setting  first it  worked after some month when i came back and tried setting is not visible does anybody  have idea to fix this i tried re installing and all but it isnt working pls help me to fix it

**Comment by eshan1234567g** [comment] 2024-04-07 10:10
i have similar issue with what ohnishat has setting is notvisible

**Comment by Ninjabrain1** [comment] 2024-04-07 21:29
This should be fixed in 1.4.3. Can you confirm that it is fixed? I want to make sure it works for everyone

**Comment by Cloud7-c** [comment] 2024-04-08 04:28
> This should be fixed in 1.4.3. Can you confirm that it is fixed? I want to make sure it works for everyone

It now works. Thanks for fixing that.

**Comment by eshan1234567g** [comment] 2024-04-08 04:44
wow this works now thank u so much for new version of ninjabrainbot

**Comment by eshan1234567g** [comment] 2024-04-08 04:45
now which tutorial should i follow to setup ninjabrainbot 1.4.3

**Closed** 2024-05-20 07:38 UTC
Labels: bug
